In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Aim is to predict the marks of students of the test data

In [55]:
# Use the file namd 'training data' to train the model

data = pd.read_excel('/content/drive/MyDrive/Training data.xlsx')
x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)

# Try plotting y_train with different features
# To get an idea whether to add some features or not
# Add some features if required in x_train

# Also do label encoding for features not represented in numbers
# refer the link if not know : https://youtu.be/589nCGeWG1w?si=t2Wa7LgbUOO4RooM

def feature_changing(x_train):
  # ---------
  x_train[x_train[:, 0] == 'no', 0] = 0
  x_train[x_train[:, 0] == 'yes', 0] = 1
  x_train[x_train[:, 1] == 'M', 1] = 0
  x_train[x_train[:, 1] == 'F', 1] = 1
  # ---------
  return x_train

x_train = feature_changing(x_train)
print(x_train)

[[0 0 2 ... 6 18 118]
 [1 0 2 ... 7 19 107]
 [1 0 3 ... 5 18 108]
 ...
 [1 0 2 ... 5 17 123]
 [1 1 1 ... 8 17 104]
 [1 0 1 ... 6 18 128]]


In [56]:
def z_score(x_train):

  # ---------
  x_mean = np.mean(x_train,axis=0)
  x_std = np.std(x_train,axis=0)
  x_train = (x_train - x_mean)/x_std
  # ---------

  return x_train,x_std,x_mean

In [57]:
def cost(x_train,y_train,w,b):

  loss = 0
  for i in range(len(x_train)):
    loss += (np.dot(x_train[i],w) + b - y_train[i])**2
  loss /= (2*len(x_train))

  return loss

In [58]:
def gradient_descent(x_train,y_train,w,b):

  # ---------
  gradient_descent_w = np.zeros(w.shape)
  gradient_descent_b = 0

  for i in range(len(x_train)):
    gradient_descent_w += (np.dot(x_train[i],w) + b - y_train[i])*x_train[i].reshape(-1,1)
    gradient_descent_b += (np.dot(x_train[i],w) + b - y_train[i])

  gradient_descent_w /= len(x_train)
  gradient_descent_b /= len(x_train)
  learning_rate = 0.01
  w -= learning_rate*gradient_descent_w
  b -= learning_rate*gradient_descent_b
  # ---------

  return w,b

In [59]:
x_train = x_train.astype(np.float64)
x_train,x_std,x_mean = z_score(x_train)

np.random.seed(2147483647)
w = np.random.randn(x_train.shape[1],1)
b = np.random.randn(1)

old_cost = 0

while abs(old_cost - cost(x_train,y_train,w,b))>0.00001:
  old_cost = cost(x_train,y_train,w,b)
  w,b = gradient_descent(x_train,y_train,w,b)
  print(f"Cost: {cost(x_train,y_train,w,b)}")

x_predict = pd.read_excel('/content/drive/MyDrive/Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('/content/drive/MyDrive/Test data.xlsx').iloc[:,8].to_numpy()

y_predict = np.dot(x_predict,w) + b

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
    accuracy += 1
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")

Cost: [2444.59024251]
Cost: [2395.91926997]
Cost: [2348.21735873]
Cost: [2301.46521352]
Cost: [2255.64392328]
Cost: [2210.73495349]
Cost: [2166.72013872]
Cost: [2123.58167523]
Cost: [2081.30211381]
Cost: [2039.86435267]
Cost: [1999.2516306]
Cost: [1959.4475201]
Cost: [1920.43592078]
Cost: [1882.20105287]
Cost: [1844.72745079]
Cost: [1807.99995689]
Cost: [1772.00371537]
Cost: [1736.72416623]
Cost: [1702.14703938]
Cost: [1668.25834888]
Cost: [1635.04438728]
Cost: [1602.49172006]
Cost: [1570.58718023]
Cost: [1539.31786294]
Cost: [1508.67112033]
Cost: [1478.63455639]
Cost: [1449.1960219]
Cost: [1420.34360959]
Cost: [1392.06564926]
Cost: [1364.35070309]
Cost: [1337.18756101]
Cost: [1310.56523617]
Cost: [1284.47296046]
Cost: [1258.90018021]
Cost: [1233.83655188]
Cost: [1209.27193787]
Cost: [1185.19640247]
Cost: [1161.60020777]
Cost: [1138.47380978]
Cost: [1115.80785454]
Cost: [1093.59317435]
Cost: [1071.82078403]
Cost: [1050.48187732]
Cost: [1029.56782332]
Cost: [1009.07016297]
Cost: [988.98